### ISSUE TITLE
trying....

### ISSUE THREAD

**Issue by jersam** [knelmes/Lego-Build-Instructions-Downloader#1]
windows 2016
i see the csv file build however no pdfs get pulled down.
any idea?

Trying 1276-1 - HELICOPTER  -  BUILD.INSTR. FOR 1276 IN
Trying 1277-1 - HOVERCRAFT WITH ICE SAWS  -  BUILD.INSTR. FOR 1277 IN
Trying 1285-1 - YELLOW RACER BOAT  -  BUILDINST. FOR 1285 IN
Trying 1286-1 - KING WITH CHART  -  {No longer listed at LEGO.com}
Trying 1288-1 - Also 4807-1  -  {No longer listed at LEGO.com}
Trying 1289-1 - SMALL CATAPULT  -  BUILD. INST FOR 1289 IN
Trying 1290-1 - VOLCANO CLIMBER  -  BUILDING INSTR. 1290
Trying 1291-1 - DIRT BIKE  -  BUILD. INSTR. 1291
Trying 1292-1 - ICE EXPLORER  -  BUILD.INSTR. 1292
Trying 1293-1 - SWAMP CRAFT  -  BUILD. INSTR. 1293

**Comment by jersam** [comment]
windows 10 seems to be fine tho but thats at home grrrrrr. would be great to have it stored at the colo.

**Comment by downloadtheworld** [comment]
Not sure. Just tried it on Server2019 and it was fine but I don't think I have a 2016 around. Try removing the error handling because it only actually handles one error and hides all the others - comment out lines 13 and 15-23

**Comment by jersam** [comment]
thanks for the pointer.

```
$url = "https://brickset.com/exportscripts/instructions"
$outputfolder = "z:\legos\"
$output = $outputfolder + 'index.csv'


Invoke-WebRequest -Uri $url -OutFile $output
$index = Import-Csv $output
foreach ($file in $index){
    $url = $file.url
    $output = $outputfolder + $file.setnumber + '.pdf'
    if(!(Test-Path $output)){
        Write-Host "Trying" $file.SetNumber - $file.Description " - " $file.Notes
        #try{
		
		add-type @"
    using System.Net;
    using System.Security.Cryptography.X509Certificates;
    public class TrustAllCertsPolicy : ICertificatePolicy {
        public bool CheckValidationResult(
            ServicePoint srvPoint, X509Certificate certificate,
            WebRequest request, int certificateProblem) {
            return true;
        }
    }
"@
[System.Net.ServicePointManager]::CertificatePolicy = New-Object TrustAllCertsPolicy

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Ssl3, [Net.SecurityProtocolType]::Tls, [Net.SecurityProtocolType]::Tls11, [Net.SecurityProtocolType]::Tls12
		
            Invoke-WebRequest -Uri $url -OutFile $output
        #} 
        #catch{
        #    switch ($_.Exception.Response.StatusCode.Value__)
        #    {
        #        403{ 
        #            Write-Host -ForegroundColor Yellow "Access Denied - Probably not on Lego's servers anymore."           
        #        }
        #    }
        #}
    }else{
        Write-Host -ForegroundColor Green $file.SetNumber "already exists, skipping"
    }
}
```

works fine now. on the invoke web request, getting a ssl error.

**Comment by downloadtheworld** [comment]
hmm. are you able to go to https://lego.com on that server? Or maybe it's just extra security in powershell on 2016.

**Comment by jersam** [comment]
lego.com work from IE. 
it might be on the WebRequest with in powershell, i think it is ssl 1.0?

**Comment by downloadtheworld** [comment]
So I think that can be condensed down to just
`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12` (before the foreach loop)
unfortunately both this and your fix require running as admin. I'll just have to add that to the readme
