### ISSUE TITLE
For sets with more than 1 instruction booklet PDF, only one is downloaded

### ISSUE THREAD

**Issue by wertercatt** [knelmes/Lego-Build-Instructions-Downloader#2]
For example, set 7199 has two instruction booklets for different parts of the set. Both are available on lego.com, but only the second one is downloaded. Without both, the archived instructions are incomplete.

**Comment by downloadtheworld** [comment]
Hello!
I was using the set name to download the files so yes, it would download one and then skip the second, thinking it had already done it. I have now added the description to the file name (with invalid characters replaced with underscores) so if you grab the new version it will download everything again including sets with multiple files, as long as the description is different.

I've also removed the rubbish error handling I had that was hiding too many errors

**Comment by wertercatt** [comment]
Thanks for the prompt patch!
